---
#- name: Ensuring OVS bridge is properly setup
#  command: docker exec openvswitch_db /usr/local/bin/kolla_ensure_openvswitch_configured {{ item.0 }} {{ item.1 }}
#  register: status
#  changed_when: status.stdout.find('changed') != -1
#  when:
#    - inventory_hostname in groups["network"]
#      or (inventory_hostname in groups["compute"] and computes_need_external_bridge | bool )
#    - not enable_onos | bool
#  with_together:
#    - "{{ neutron_bridge_name.split(',') }}"
#    - "{{ neutron_external_interface.split(',') }}"

- name: Ensuring OVS EXT bridge is properly setup
  command: docker exec openvswitch_db /usr/local/bin/kolla_ensure_openvswitch_configured {{ item.0 }} {{ item.1 }}
  register: status
  changed_when: status.stdout.find('changed') != -1
  when:
    - inventory_hostname in groups["network"]
      or (inventory_hostname in groups["compute"] and computes_need_ext_bridge | bool )
  with_together:
    - "{{ neutron_external_ovs_bridge.split(',') }}"
    - "{{ neutron_external_interface.split(',') }}"

- name: Ensuring OVS INT bridge is properly setup
  command: docker exec openvswitch_db /usr/local/bin/kolla_ensure_openvswitch_configured {{ item.0 }} {{ item.1 }}
  register: status
  changed_when: status.stdout.find('changed') != -1
  when:
    - inventory_hostname in groups["network"]
      or (inventory_hostname in groups["compute"] and computes_need_int_bridge | bool )
  with_together:
    - "{{ neutron_internal_ovs_bridge.split(',') }}"
    - "{{ neutron_internal_interface.split(',') }}"
